---
# Source: ako-crd-operator/templates/manager/manager.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ako-crd-operator
  namespace: default
  labels:
    app.kubernetes.io/version: "2.1.1"
    helm.sh/chart: "2.1.1"
    app.kubernetes.io/name: ako-crd-operator
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    control-plane: controller-manager
spec:
  replicas:  1
  selector:
    matchLabels:
      app.kubernetes.io/name: ako-crd-operator
      app.kubernetes.io/instance: release-name
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/version: "2.1.1"
        helm.sh/chart: "2.1.1"
        app.kubernetes.io/name: ako-crd-operator
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        control-plane: controller-manager
    spec:
      containers:
        - name: ako-crd-operator
          args:
            - --health-probe-bind-address=:8081
          command:
            - /manager
          image: projects.packages.broadcom.com/ako/ako-crd-operator:2.1.1
          imagePullPolicy: IfNotPresent
          
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","/var/pre_stop_hook.sh"]
          env:
            - name: CTRL_IPADDRESS
              valueFrom:
                configMapKeyRef:
                  name: avi-k8s-config
                  key: controllerIP
            - name: DEDICATED_TENANT_MODE
              valueFrom:
                configMapKeyRef:
                  name: avi-k8s-config
                  key: dedicatedTenantMode
            - name: CTRL_VERSION
              valueFrom:
                configMapKeyRef:
                  name: avi-k8s-config
                  key: controllerVersion
            - name: CLOUD_NAME
              valueFrom:
                configMapKeyRef:
                  name: avi-k8s-config
                  key: cloudName
            - name: TENANT_NAME
              valueFrom:
                configMapKeyRef:
                  name: avi-k8s-config
                  key: tenantName
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: avi-k8s-config
                  key: clusterName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: avi-k8s-config
                  key: logLevel
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            
            - name: LOG_FILE_PATH
              value: /log
            - name: LOG_FILE_NAME
              value: ako-crd-operator.log
          livenessProbe:
            
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            
            limits:
              cpu: 256m
              memory: 128Mi
            requests:
              cpu: 128m
              memory: 64Mi
          securityContext:
            
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
      securityContext:
        
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: ako-crd-operator
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        
        []
