apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineService
metadata:
  name: chris-clusterip
spec:
  selector:
    vm-selector: test-vm 
  type: ClusterIP
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chris-ingress
spec:
  ingressClassName: avi-lb
  tls:
  - hosts:
      - ingress6.k8s.sfo.rainpole.io
    secretName: ingress6-tls
  rules:
    - host: ingress6.k8s.sfo.rainpole.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: chris-clusterip
                port:
                  number: 80
