apiVersion: vmoperator.vmware.com/v1alpha4
kind: VirtualMachine
metadata:
  name: argocd-demo-vm01 
  labels:
    vm-selector: test-vm
spec:
  className: best-effort-small
  imageName: vmi-59821c43b5b56c81a 
  storageClass: vsan-default-storage-policy
  powerState: PoweredOn 
  bootstrap:
    cloudInit:
      cloudConfig:
        defaultUserEnabled: true
        runcmd:
        - /usr/bin/apt update
        - /usr/bin/apt-get install -y apache2 php php-mysql libapache2-mod-php php-cli
          php-common php-intl php-gd php-mbstring php-xml php-zip php-curl php-xmlrpc
          unzip open-vm-tools
        users:
        - lock_passwd: false
          name: aviuser
          passwd:
            key: aviuser-passwd
            name: app2-bootstrap-secret
          sudo: ALL=(ALL) NOPASSWD:ALL
