apiVersion: v1
kind: Service
metadata:
  name: web-front-1
spec:
  selector:
    app: web-front1
  ports:
    - name: port8080
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer 
