---
# Source: ako-crd-operator/templates/rbac/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/version: "2.1.1"
    helm.sh/chart: "2.1.1"
    app.kubernetes.io/name: ako-crd-operator
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
  name: ako-crd-operator-role
rules:
  - apiGroups:
      - ako.vmware.com
    resources:
      - healthmonitors
      - healthmonitors/status
      - healthmonitors/finalizers
      - routebackendextensions
      - routebackendextensions/status
      - pkiprofiles
      - pkiprofiles/status
      - pkiprofiles/finalizers
    verbs:
      - '*'
  - apiGroups:
      - ako.vmware.com
    resources:
      - applicationprofiles
      - applicationprofiles/status
      - applicationprofiles/finalizers
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
